ERROR: silver layer
the member grouping and member delta table was created at silver layer in the delta live tables. but due to the runtime cache the records are not extracted and the pipeline failed silently.